### ISSUE TITLE
Wrong CLA?

### ISSUE THREAD

**Issue by matt-scientist** [Zondax/ledger-thorchain-js#2]
In `common.js` I'm seeing:
```
export const CLA = 0x89;
```

When using this package I'm receiving a `CLA_NOT_SUPPORTED` on all calls. In the [ledger app code](https://github.com/thorchain/ledger-thorchain/blob/eb089ed6d4507b028bcafa54e1761e0b30e47bdd/docs/APDUSPEC.md)
I'm seeing a CLA of `0x55 `, which works when I manually call `send` on the transport - should this package be using CLA `0x55` ?

**Comment by jleni** [comment]
No, CLA = 0x55 corresponds to the Cosmos app.
We don't use the same CLA for different apps. The implementation we made uses 0x89. 

We are not involved in that fork: https://github.com/thorchain/ledger-thorchain/
